allowBuilds:
  '0': '@deepseek-ai/dsh-subprocess-local'
  '1': koffi
  '2': node-pty
  '@deepseek-ai/dsh-subprocess-local': set this to true or false
  koffi: set this to true or false
  node-pty: set this to true or false
